name: Apocalypse
main: org.imaginecraft.apocalypse.Apocalypse
version: ${project.version}
author: [sirrus86, beschio]
depend: [ProtocolLib]

commands:
    apocalypse:
        description: ...
        aliases: [apoc]
        usage: /apoc

permissions:
    apocalypse.admin:
        description: Gives user complete control of the Apocalypse plugin.
        default: op
        children:
            apocalypse.removeteam: true
            apocalypse.setoption: true
            apocalypse.settown: true
            apocalypse.setworld: true
            apocalypse.start: true
            apocalypse.testboss: true
            apocalypse.testsiege: true
    apocalypse.addteam:
        description: Allows user to add teams to the event.
        default: true
    apocalypse.chat:
        description: Allows user to toggle event chat.
        default: true
    apocalypse.join:
        description: Allows user to join an Apocalypse event.
        default: true
    apocalypse.leave:
        description: Allows user to leave an Apocalypse event.
        default: true
    apocalypse.removeteam:
        description: Allows user to remove teams from the event.
        default: false
    apocalypse.setoption:
        description: Allows user to view and modify plugin configuration options.
        default: false
    apocalypse.settown:
        description: Allows user to set a given team's town location.
        default: false
    apocalypse.setworld:
        description: Allows user to set the Apocalypse event's world.
        default: false
    apocalypse.start:
        description: Allows user to start the Apocalypse event.
        default: false
    apocalypse.testboss:
        description: Allows user to spawn in and test bosses.
        default: false
    apocalypse.testsiege:
        description: Allows user to spawn in and test sieges.
        default: false